version: '3'
services:
  leafy-postgres:
    # image: leafy-postgres:5.0.0-compose
    image: dolcelab/leafy-postgres:f306e748aa97463ea0c536844de31e583dd7e538
    volumes:
      - mydata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: always

  leafy-backend:
    build: ./leafy-backend
    image: leafy-backend:5.0.0-compose
    environment:
      - DB_URL=leafy-postgres
    depends_on:
      - leafy-postgres
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure
      
  leafy-front:
    # image: leafy-front:5.0.0-compose
    image: dolcelab/leafy-frontend:ad55f897ce62fd43299740f1ec58b28cc768d082
    environment:
      - BACKEND_HOST=leafy-backend
    ports:
      - 80:80
    depends_on:
      - leafy-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: on-failure

volumes:
  mydata: